export const dummyData = [
  {
    id: 0,
    name: "Sofia Welch",
    userName: "sofia71",
    avatar: "https://i.pravatar.cc/150?u=sofiawelch",
    isActive: true,
    role: "Frontend Developer",
    email: "sofia83@untitled.ui",
    teams: ["tech", "marketing", "rnd"],
  },
  {
    id: 1,
    name: "Mrs. Talia Schamberger",
    userName: "talia.schamberger72",
    avatar: "https://i.pravatar.cc/150?u=taliaschamberger",
    isActive: true,
    role: "Frontend Developer",
    email: "talia_schamberger93@untitled.ui",
    teams: ["rnd", "marketing", "design"],
  },
  {
    id: 2,
    name: "Tomas Beahan",
    userName: "tomas.beahan48",
    avatar: "https://i.pravatar.cc/150?u=tomasbeahan",
    isActive: false,
    role: "UX Researcher",
    email: "tomas.beahan@untitled.ui",
    teams: ["tech", "marketing", "design", "qa", "product"],
  },
  {
    id: 3,
    name: "Mrs. Louisa Cormier",
    userName: "louisa.cormier5",
    avatar: "https://i.pravatar.cc/150?u=louisacormier",
    isActive: true,
    role: "Frontend Developer",
    email: "louisa_cormier98@untitled.ui",
    teams: ["product"],
  },
  {
    id: 4,
    name: "Florida Beatty",
    userName: "florida.beatty",
    avatar: "https://i.pravatar.cc/150?u=floridabeatty",
    isActive: true,
    role: "Frontend Developer",
    email: "florida1@untitled.ui",
    teams: ["tech", "marketing", "qa", "product"],
  },
  {
    id: 5,
    name: "Julian Olson",
    userName: "julian48",
    avatar: "https://i.pravatar.cc/150?u=julianolson",
    isActive: false,
    role: "Frontend Developer",
    email: "julian.olson69@untitled.ui",
    teams: ["marketing", "tech", "rnd", "product", "qa", "design"],
  },
  {
    id: 6,
    name: "Dewayne O'Connell II",
    userName: "dewayne18",
    avatar: "https://i.pravatar.cc/150?u=dewayneo'connell",
    isActive: true,
    role: "Backend Developer",
    email: "dewayne.oconnell@untitled.ui",
    teams: ["rnd", "design", "qa", "marketing"],
  },
  {
    id: 7,
    name: "Alicia Willms",
    userName: "alicia48",
    avatar: "https://i.pravatar.cc/150?u=aliciawillms",
    isActive: true,
    role: "Backend Developer",
    email: "alicia_willms57@untitled.ui",
    teams: ["product", "tech", "qa"],
  },
  {
    id: 8,
    name: "Isabelle Hahn",
    userName: "isabelle.hahn54",
    avatar: "https://i.pravatar.cc/150?u=isabellehahn",
    isActive: true,
    role: "Data Scientist",
    email: "isabelle.hahn34@untitled.ui",
    teams: ["design"],
  },
  {
    id: 9,
    name: "Estelle O'Connell",
    userName: "estelle.oconnell",
    avatar: "https://i.pravatar.cc/150?u=estelleo'connell",
    isActive: false,
    role: "Marketing Manager",
    email: "estelle_oconnell@untitled.ui",
    teams: ["qa", "rnd", "marketing", "design", "product"],
  },
  {
    id: 10,
    name: "Jade Sporer",
    userName: "jade.sporer67",
    avatar: "https://i.pravatar.cc/150?u=jadesporer",
    isActive: true,
    role: "Product Manager",
    email: "jade.sporer8@untitled.ui",
    teams: ["marketing", "design", "tech", "qa", "product"],
  },
  {
    id: 11,
    name: "Miss Lavon Haag",
    userName: "lavon_haag",
    avatar: "https://i.pravatar.cc/150?u=lavonhaag",
    isActive: false,
    role: "Data Scientist",
    email: "lavon44@untitled.ui",
    teams: ["product", "marketing", "qa", "rnd", "design"],
  },
  {
    id: 12,
    name: "Eric Brekke",
    userName: "eric_brekke48",
    avatar: "https://i.pravatar.cc/150?u=ericbrekke",
    isActive: false,
    role: "Product Manager",
    email: "eric2@untitled.ui",
    teams: ["qa", "marketing"],
  },
  {
    id: 13,
    name: "Rafael Erdman",
    userName: "rafael_erdman46",
    avatar: "https://i.pravatar.cc/150?u=rafaelerdman",
    isActive: true,
    role: "Backend Developer",
    email: "rafael52@untitled.ui",
    teams: ["marketing", "product"],
  },
  {
    id: 14,
    name: "Nyah Collier",
    userName: "nyah_collier",
    avatar: "https://i.pravatar.cc/150?u=nyahcollier",
    isActive: false,
    role: "Backend Developer",
    email: "nyah.collier79@untitled.ui",
    teams: ["marketing", "tech", "design", "rnd", "product", "qa"],
  },
  {
    id: 15,
    name: "Miss Modesta Turcotte",
    userName: "modesta27",
    avatar: "https://i.pravatar.cc/150?u=modestaturcotte",
    isActive: false,
    role: "Frontend Developer",
    email: "modesta.turcotte15@untitled.ui",
    teams: ["marketing", "qa"],
  },
  {
    id: 16,
    name: "Mrs. Jazmyne Harber",
    userName: "jazmyne44",
    avatar: "https://i.pravatar.cc/150?u=jazmyneharber",
    isActive: false,
    role: "Backend Developer",
    email: "jazmyne_harber3@untitled.ui",
    teams: ["rnd", "qa"],
  },
  {
    id: 17,
    name: "Elvera Daugherty",
    userName: "elvera39",
    avatar: "https://i.pravatar.cc/150?u=elveradaugherty",
    isActive: true,
    role: "Product Designer",
    email: "elvera.daugherty@untitled.ui",
    teams: ["rnd", "product", "marketing", "tech", "design", "qa"],
  },
  {
    id: 18,
    name: "Amelie Boyer",
    userName: "amelie_boyer",
    avatar: "https://i.pravatar.cc/150?u=amelieboyer",
    isActive: true,
    role: "Marketing Manager",
    email: "amelie_boyer87@untitled.ui",
    teams: ["product"],
  },
  {
    id: 19,
    name: "Dr. Sonny Collins",
    userName: "sonny.collins99",
    avatar: "https://i.pravatar.cc/150?u=sonnycollins",
    isActive: true,
    role: "Product Designer",
    email: "sonny78@untitled.ui",
    teams: ["design", "product", "qa"],
  },
  {
    id: 20,
    name: "Ottis Swaniawski",
    userName: "ottis4",
    avatar: "https://i.pravatar.cc/150?u=ottisswaniawski",
    isActive: false,
    role: "Marketing Manager",
    email: "ottis34@untitled.ui",
    teams: ["product", "rnd", "tech", "marketing"],
  },
  {
    id: 21,
    name: "Alexanne Tremblay Jr.",
    userName: "alexanne9",
    avatar: "https://i.pravatar.cc/150?u=alexannetremblay",
    isActive: false,
    role: "Frontend Developer",
    email: "alexanne77@untitled.ui",
    teams: ["rnd", "tech", "design"],
  },
  {
    id: 22,
    name: "Ellen Senger",
    userName: "ellen_senger42",
    avatar: "https://i.pravatar.cc/150?u=ellensenger",
    isActive: false,
    role: "UX Researcher",
    email: "ellen_senger@untitled.ui",
    teams: ["rnd", "qa", "marketing", "design"],
  },
  {
    id: 23,
    name: "Miss Douglas Gottlieb II",
    userName: "douglas.gottlieb17",
    avatar: "https://i.pravatar.cc/150?u=douglasgottlieb",
    isActive: true,
    role: "UX Researcher",
    email: "douglas74@untitled.ui",
    teams: ["design", "tech"],
  },
  {
    id: 24,
    name: "Hilton Wiegand",
    userName: "hilton_wiegand44",
    avatar: "https://i.pravatar.cc/150?u=hiltonwiegand",
    isActive: true,
    role: "Marketing Manager",
    email: "hilton_wiegand@untitled.ui",
    teams: ["product", "qa", "marketing", "tech"],
  },
  {
    id: 25,
    name: "Zakary Glover",
    userName: "zakary_glover",
    avatar: "https://i.pravatar.cc/150?u=zakaryglover",
    isActive: false,
    role: "Backend Developer",
    email: "zakary_glover49@untitled.ui",
    teams: ["design", "product"],
  },
  {
    id: 26,
    name: "Otto Hermann",
    userName: "otto_hermann2",
    avatar: "https://i.pravatar.cc/150?u=ottohermann",
    isActive: true,
    role: "Data Scientist",
    email: "otto_hermann97@untitled.ui",
    teams: ["product", "tech", "design", "marketing", "rnd"],
  },
  {
    id: 27,
    name: "Chaya Harber I",
    userName: "chaya0",
    avatar: "https://i.pravatar.cc/150?u=chayaharber",
    isActive: false,
    role: "Frontend Developer",
    email: "chaya.harber7@untitled.ui",
    teams: ["rnd", "marketing", "design", "product", "tech"],
  },
  {
    id: 28,
    name: "Francisco Reynolds",
    userName: "francisco.reynolds74",
    avatar: "https://i.pravatar.cc/150?u=franciscoreynolds",
    isActive: false,
    role: "Product Designer",
    email: "francisco43@untitled.ui",
    teams: ["tech"],
  },
  {
    id: 29,
    name: "Destini Lemke",
    userName: "destini93",
    avatar: "https://i.pravatar.cc/150?u=destinilemke",
    isActive: true,
    role: "Product Manager",
    email: "destini_lemke81@untitled.ui",
    teams: ["design", "tech", "marketing", "rnd", "product", "qa"],
  },
  {
    id: 30,
    name: "Dennis Stokes Sr.",
    userName: "dennis_stokes32",
    avatar: "https://i.pravatar.cc/150?u=dennisstokes",
    isActive: true,
    role: "Product Manager",
    email: "dennis.stokes53@untitled.ui",
    teams: ["marketing", "product", "qa"],
  },
  {
    id: 31,
    name: "Eloise Kunze",
    userName: "eloise97",
    avatar: "https://i.pravatar.cc/150?u=eloisekunze",
    isActive: false,
    role: "Data Scientist",
    email: "eloise_kunze29@untitled.ui",
    teams: ["rnd"],
  },
  {
    id: 32,
    name: "Jacynthe Jast",
    userName: "jacynthe_jast",
    avatar: "https://i.pravatar.cc/150?u=jacynthejast",
    isActive: false,
    role: "Product Manager",
    email: "jacynthe82@untitled.ui",
    teams: ["tech", "design"],
  },
  {
    id: 33,
    name: "Melody Shields",
    userName: "melody_shields",
    avatar: "https://i.pravatar.cc/150?u=melodyshields",
    isActive: true,
    role: "UX Researcher",
    email: "melody6@untitled.ui",
    teams: ["tech", "marketing", "product", "rnd", "qa", "design"],
  },
  {
    id: 34,
    name: "Miguel Welch",
    userName: "miguel_welch93",
    avatar: "https://i.pravatar.cc/150?u=miguelwelch",
    isActive: true,
    role: "Product Designer",
    email: "miguel18@untitled.ui",
    teams: ["product", "qa", "tech", "rnd"],
  },
  {
    id: 35,
    name: "Mrs. Willa Leannon",
    userName: "willa45",
    avatar: "https://i.pravatar.cc/150?u=willaleannon",
    isActive: false,
    role: "Frontend Developer",
    email: "willa.leannon@untitled.ui",
    teams: ["product"],
  },
  {
    id: 36,
    name: "Lizeth Lang",
    userName: "lizeth.lang59",
    avatar: "https://i.pravatar.cc/150?u=lizethlang",
    isActive: false,
    role: "UX Researcher",
    email: "lizeth.lang13@untitled.ui",
    teams: ["rnd", "product", "design", "tech", "qa", "marketing"],
  },
  {
    id: 37,
    name: "Roman Mann",
    userName: "roman61",
    avatar: "https://i.pravatar.cc/150?u=romanmann",
    isActive: false,
    role: "Data Scientist",
    email: "roman77@untitled.ui",
    teams: ["marketing", "product", "qa", "tech", "design"],
  },
  {
    id: 38,
    name: "Buck Emmerich",
    userName: "buck.emmerich",
    avatar: "https://i.pravatar.cc/150?u=buckemmerich",
    isActive: false,
    role: "Frontend Developer",
    email: "buck_emmerich26@untitled.ui",
    teams: ["marketing", "tech", "design", "product"],
  },
  {
    id: 39,
    name: "Jeremy Bashirian",
    userName: "jeremy_bashirian",
    avatar: "https://i.pravatar.cc/150?u=jeremybashirian",
    isActive: true,
    role: "Data Scientist",
    email: "jeremy.bashirian@untitled.ui",
    teams: ["marketing", "rnd", "qa", "product", "design"],
  },
  {
    id: 40,
    name: "Lucio Brakus",
    userName: "lucio73",
    avatar: "https://i.pravatar.cc/150?u=luciobrakus",
    isActive: false,
    role: "Product Designer",
    email: "lucio_brakus37@untitled.ui",
    teams: ["marketing", "design", "rnd"],
  },
  {
    id: 41,
    name: "Miss Jarrett Rippin",
    userName: "jarrett_rippin75",
    avatar: "https://i.pravatar.cc/150?u=jarrettrippin",
    isActive: false,
    role: "Product Designer",
    email: "jarrett.rippin@untitled.ui",
    teams: ["design"],
  },
  {
    id: 42,
    name: "Mr. Elisha Emard PhD",
    userName: "elisha.emard68",
    avatar: "https://i.pravatar.cc/150?u=elishaemard",
    isActive: true,
    role: "Product Designer",
    email: "elisha77@untitled.ui",
    teams: ["tech", "rnd", "design", "marketing", "product", "qa"],
  },
  {
    id: 43,
    name: "Mrs. Rogelio Wolf",
    userName: "rogelio48",
    avatar: "https://i.pravatar.cc/150?u=rogeliowolf",
    isActive: true,
    role: "Backend Developer",
    email: "rogelio_wolf22@untitled.ui",
    teams: ["marketing", "product", "qa", "design"],
  },
  {
    id: 44,
    name: "Antonina Schoen",
    userName: "antonina66",
    avatar: "https://i.pravatar.cc/150?u=antoninaschoen",
    isActive: false,
    role: "UX Researcher",
    email: "antonina.schoen99@untitled.ui",
    teams: ["marketing", "rnd", "product", "tech", "qa"],
  },
  {
    id: 45,
    name: "Adriana Weimann",
    userName: "adriana91",
    avatar: "https://i.pravatar.cc/150?u=adrianaweimann",
    isActive: false,
    role: "Product Manager",
    email: "adriana.weimann0@untitled.ui",
    teams: ["tech", "product", "design"],
  },
  {
    id: 46,
    name: "Alessandro Emard",
    userName: "alessandro.emard",
    avatar: "https://i.pravatar.cc/150?u=alessandroemard",
    isActive: false,
    role: "Marketing Manager",
    email: "alessandro.emard63@untitled.ui",
    teams: ["qa", "design", "product", "tech"],
  },
  {
    id: 47,
    name: "Chester Rutherford",
    userName: "chester77",
    avatar: "https://i.pravatar.cc/150?u=chesterrutherford",
    isActive: true,
    role: "Marketing Manager",
    email: "chester.rutherford21@untitled.ui",
    teams: ["tech", "product"],
  },
  {
    id: 48,
    name: "Madie Quigley",
    userName: "madie51",
    avatar: "https://i.pravatar.cc/150?u=madiequigley",
    isActive: false,
    role: "Backend Developer",
    email: "madie_quigley47@untitled.ui",
    teams: ["design", "qa"],
  },
  {
    id: 49,
    name: "General Spencer",
    userName: "general84",
    avatar: "https://i.pravatar.cc/150?u=generalspencer",
    isActive: false,
    role: "Frontend Developer",
    email: "general_spencer46@untitled.ui",
    teams: ["product", "tech", "rnd", "design"],
  },
  {
    id: 50,
    name: "Mathew Rodriguez",
    userName: "mathew.rodriguez",
    avatar: "https://i.pravatar.cc/150?u=mathewrodriguez",
    isActive: false,
    role: "Product Designer",
    email: "mathew32@untitled.ui",
    teams: ["product", "qa"],
  },
  {
    id: 51,
    name: "Aaron Mertz",
    userName: "aaron.mertz40",
    avatar: "https://i.pravatar.cc/150?u=aaronmertz",
    isActive: true,
    role: "Product Designer",
    email: "aaron.mertz@untitled.ui",
    teams: ["qa", "marketing", "product"],
  },
  {
    id: 52,
    name: "Regan Metz",
    userName: "regan_metz",
    avatar: "https://i.pravatar.cc/150?u=reganmetz",
    isActive: false,
    role: "Backend Developer",
    email: "regan53@untitled.ui",
    teams: ["rnd"],
  },
  {
    id: 53,
    name: "Kamille Sauer",
    userName: "kamille8",
    avatar: "https://i.pravatar.cc/150?u=kamillesauer",
    isActive: false,
    role: "Product Designer",
    email: "kamille21@untitled.ui",
    teams: ["product", "marketing", "rnd", "tech", "design", "qa"],
  },
  {
    id: 54,
    name: "Earl Beahan",
    userName: "earl38",
    avatar: "https://i.pravatar.cc/150?u=earlbeahan",
    isActive: false,
    role: "Product Manager",
    email: "earl50@untitled.ui",
    teams: ["rnd", "design", "marketing", "product"],
  },
  {
    id: 55,
    name: "Kitty Boyle",
    userName: "kitty_boyle",
    avatar: "https://i.pravatar.cc/150?u=kittyboyle",
    isActive: false,
    role: "Frontend Developer",
    email: "kitty_boyle@untitled.ui",
    teams: ["rnd", "marketing"],
  },
  {
    id: 56,
    name: "Kristoffer Marquardt",
    userName: "kristoffer45",
    avatar: "https://i.pravatar.cc/150?u=kristoffermarquardt",
    isActive: false,
    role: "Product Designer",
    email: "kristoffer62@untitled.ui",
    teams: ["qa"],
  },
  {
    id: 57,
    name: "Ruby Sipes",
    userName: "ruby45",
    avatar: "https://i.pravatar.cc/150?u=rubysipes",
    isActive: false,
    role: "Product Designer",
    email: "ruby_sipes@untitled.ui",
    teams: ["rnd", "tech", "design", "product", "marketing"],
  },
  {
    id: 58,
    name: "Grace Schinner II",
    userName: "grace_schinner",
    avatar: "https://i.pravatar.cc/150?u=graceschinner",
    isActive: false,
    role: "Frontend Developer",
    email: "grace.schinner58@untitled.ui",
    teams: ["product", "tech", "rnd", "qa", "marketing", "design"],
  },
  {
    id: 59,
    name: "Haleigh Oberbrunner",
    userName: "haleigh_oberbrunner",
    avatar: "https://i.pravatar.cc/150?u=haleighoberbrunner",
    isActive: true,
    role: "UX Researcher",
    email: "haleigh.oberbrunner@untitled.ui",
    teams: ["rnd", "design", "product"],
  },
];
